KNOWN_DOCS = {
    "react": "https://react.dev/learn",
    "fastapi": "https://fastapi.tiangolo.com",
    "langchain": "https://python.langchain.com/docs/introduction",
    "tailwind": "https://tailwindcss.com/docs/installation",
    "pandas": "https://pandas.pydata.org/docs/user_guide/index.html",
    "nextjs": "https://nextjs.org/docs",
    "express": "https://expressjs.com/en/guide/routing.html",
    "prisma": "https://www.prisma.io/docs/getting-started",
    "redux": "https://redux-toolkit.js.org/introduction/getting-started",
    "vue": "https://vuejs.org/guide/introduction",
    "django": "https://docs.djangoproject.com/en/stable/intro/overview",
    "typescript": "https://www.typescriptlang.org/docs/handbook/intro.html",
    "mongodb": "https://www.mongodb.com/docs/manual/introduction",
    "docker": "https://docs.docker.com/get-started/overview",
    "axios": "https://axios-http.com/docs/intro",
    "sqlalchemy": "https://docs.sqlalchemy.org/en/20/tutorial/index.html",
    "pydantic": "https://docs.pydantic.dev/latest",
    "pytest": "https://docs.pytest.org/en/stable/getting-started.html",
}
